site:
  ## The title of your website.
  title: MarkHub

  ## The URL of your website.
  url: 'https://fdxx.github.io'

  ## HTML lang Attribute. Use a 2-letter ISO-639-1 code or optionally its variant.
  ## eg. en, zh-CN 
  language: en

  ## The root directory of your website.
  ## If your website is in a subdirectory (such as http://example.org/blog), set root to /blog/. And 
  ## add `/blog/` to the absolute path of the following configuration.
  root: '/markhub/'

  ## Default value for the article author if you don't specify one explicitly in the Front-matter.
  author: fdxx

  ## favicon link
  favicon: '/markhub/assets/images/favicon.ico'

  ## posts file directory.
  posts_dir: 'source/posts'

  ## Where to generate static web files.
  push_dir: 'public'

  ## Additional files/folders to copy after the build is complete, such as favicon, etc.
  copy_dir:
    - source: 'source/assets'
      dest: 'public/assets'

  ## Number of posts displayed on each page. 
  pageSize:
    home: 10
    archive: 30

  ## CSS and JS links to add.
  ## If you don't need math, comment out katex to optimize page loading speed.
  css: 
    - 'https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.6.1/github-markdown.min.css'
    - 'https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.min.css'
    - 'https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css'
    - '/markhub/assets/css/highlight-github.css'
    - '/markhub/assets/css/main.css'
  js:
    - 'https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js'
    - '/markhub/assets/js/main.js'

## The name and link of the navigation menu.
navigation:
  Home:
    link: '/markhub/'
  Archive:
    link: '/markhub/archive/'
  Tags:
    link: '/markhub/tags/'
  About:
    link: '/markhub/about/'

## The text displayed in the footer. Raw HTML syntax.
footer:
  content: '<p>2024 © fdxx. Built with <a href="https://github.com/fdxx/markhub">markhub</a></p>'

## Translate text.
translate:
  published: 'Published'
  readmore: 'Read more'
  pageviews: 'Pageviews'


## pagecounter. Show post views
## https://github.com/fdxx/pagecounter
pagecounter:
  enable: true
  ## server uri
  server: 'https://pagecounter.fdxx.workers.dev/pageviews'

  ## Specify domain value, default value: window.location.hostname
  domain: 'fdxx.github.io'


## A comments system powered by GitHub Discussions.
## https://giscus.app
giscus:
  enable: true
  data-repo: "fdxx/markhub"
  data-repo-id: "R_kgDOMq6IwA"
  data-category: "Announcements"
  data-category-id: "DIC_kwDOMq6IwM4CiG-h"
  data-mapping: "pathname"
  ## default value: config.site.language
  ## data-lang: "en"

## Waline comments system
## https://waline.js.org
waline:
  enable: false

  # Waline server address url, you should set this to your own link
  serverURL: https://waline.vercel.app

  # Waline library CDN url, you can set this to your preferred CDN
  libUrl: https://unpkg.com/@waline/client@v3/dist/waline.js

  # Waline CSS styles CDN url, you can set this to your preferred CDN
  cssUrl: https://unpkg.com/@waline/client@v3/dist/waline.css

  # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`.
  pageview: true

  # Custom locales
  locale:
    placeholder: 'Say something..'

  dark: 'auto'
  # Custom emoji
  # emoji:
  #   - https://unpkg.com/@waline/emojis@1.1.0/weibo
  #   - https://unpkg.com/@waline/emojis@1.1.0/alus
  #   - https://unpkg.com/@waline/emojis@1.1.0/bilibili
  #   - https://unpkg.com/@waline/emojis@1.1.0/qq
  #   - https://unpkg.com/@waline/emojis@1.1.0/tieba
  #   - https://unpkg.com/@waline/emojis@1.1.0/tw-emoji

  # Comment information, valid meta are nick, mail and link
  # meta:
  #   - nick
  #   - mail
  #   - link

  # Set required meta field, e.g.: [nick] | [nick, mail]
  # requiredMeta:
  #   - nick

  # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP, fr-FR
  # default value: config.site.language
  # lang: en

  # Word limit, no limit when setting to 0
  # wordLimit: 0

  # Whether enable login, can choose from 'enable', 'disable' and 'force'
  # login: enable

  # comment per page
  # pageSize: 10

  # turnstileKey: ''
  #
  # reaction:
  #   - 'https://unpkg.com/@waline/emojis@1.2.0/tieba/tieba_agree.png'
  #   - 'https://unpkg.com/@waline/emojis@1.2.0/tieba/tieba_sunglasses.png'
  #   - 'https://unpkg.com/@waline/emojis@1.2.0/tieba/tieba_look_down.png'
  #   - 'https://unpkg.com/@waline/emojis@1.2.0/tieba/tieba_antic.png'
  #   - 'https://unpkg.com/@waline/emojis@1.2.0/tieba/tieba_pick_nose.png'
      

